In [1]:
from pymmcore_slm_sim import SimSLMDevice
from pymmcore_camera_sim import SimCameraDevice, test
from pymmcore_stage_sim import SimStageDevice
from pymmcore_plus.experimental.unicore import UniMMCore
import napari

import numpy as np
import matplotlib.pyplot as plt

from PIL import Image, ImageDraw, ImageFont
from skimage.io import imsave
import os

pygame-ce 2.5.5 (SDL 2.32.6, Python 3.13.5)


In [3]:
import napari
viewer = napari.Viewer()


In [4]:
test()

Note: Provide core to the SimCameraDevice constructor to use SLM features
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0

C:\Users\dario\anaconda3\envs\opto-loop\Lib\site-packages\vispy\visuals\_scalable_textures.py:297: RuntimeWarning: overflow encountered in scalar subtract
  clim_min = (clim_min - range_min) / full_range


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

In [4]:
core = UniMMCore()

In [ ]:
core.loadPyDevice("Camera", SimCameraDevice())
core.initializeDevice("Camera")

In [ ]:
core.setCameraDevice("Camera")

In [ ]:
core.setExposure(50)

In [ ]:
core.startContinuousSequenceAcquisition(10)

In [ ]:
core.snapImage()

In [ ]:
core.getImage()

In [2]:
core = UniMMCore()
core.loadPyDevice("Camera", SimCameraDevice(core=core))
core.initializeDevice("Camera")
core.setCameraDevice("Camera")
core.loadPyDevice("XYStage", SimStageDevice())
core.initializeDevice("Camera")
core.initializeDevice("XYStage")
core.setCameraDevice("Camera")
core.setXYStageDevice("XYStage")
core.setExposure(50)

viewer = napari.Viewer()
viewer.window.add_plugin_dock_widget(plugin_name='napari-micromanager')

napari.run()

C:\Users\dario\anaconda3\envs\opto-loop\Lib\site-packages\napari_micromanager\main_window.py:51: FutureWarning: The `_dock_widgets` property is private and should not be used in any plugin code. Please use the `dock_widgets` property instead.
  if "MinMax" not in getattr(self.viewer.window, "_dock_widgets", []):


In [2]:
import napari
viewer = napari.Viewer()
viewer.window.add_plugin_dock_widget(
    plugin_name='napari-micromanager',
)
core = UniMMCore()
core.loadPyDevice("Camera", SimCameraDevice())
#core.loadPyDevice("XYStage", SimStageDevice())
core.initializeDevice("Camera")
#core.initializeDevice("XYStage")
core.setCameraDevice("Camera")
#core.setXYStageDevice("XYStage")
core.setExposure(50)
#core.startContinuousSequenceAcquisition(10)
napari.run()

Note: Provide core to the SimCameraDevice constructor to use SLM features


C:\Users\dario\anaconda3\envs\opto-loop\Lib\site-packages\napari_micromanager\main_window.py:51: FutureWarning: The `_dock_widgets` property is private and should not be used in any plugin code. Please use the `dock_widgets` property instead.
  if "MinMax" not in getattr(self.viewer.window, "_dock_widgets", []):


In [3]:
core.getXYPosition()

RuntimeError: No device with label ""