In [ ]:
from pymmcore_slm_sim import SimSLMDevice
from pymmcore_camera_sim import SimCameraDevice, test
from pymmcore_stage_sim import SimStageDevice
from pymmcore_plus.experimental.unicore import UniMMCore
import napari

import numpy as np
#import matplotlib.pyplot as plt

from PIL import Image, ImageDraw, ImageFont
from skimage.io import imsave
import os

from pymmcore_state_sim import SimStateDevice

In [ ]:
import napari
viewer = napari.Viewer()


In [ ]:
test()

In [ ]:
core = UniMMCore()

In [ ]:
core.loadPyDevice("Camera", SimCameraDevice())
core.initializeDevice("Camera")

In [ ]:
core.setCameraDevice("Camera")

In [ ]:
core.setExposure(50)

In [ ]:
core.startContinuousSequenceAcquisition(10)

In [ ]:
core.snapImage()

In [ ]:
core.getImage()

In [ ]:
core = UniMMCore()
core.loadPyDevice("Camera", SimCameraDevice(core=core))
core.initializeDevice("Camera")
core.setCameraDevice("Camera")
core.loadPyDevice("XYStage", SimStageDevice())
core.initializeDevice("Camera")
core.initializeDevice("XYStage")
core.setCameraDevice("Camera")
core.setXYStageDevice("XYStage")
core.setExposure(50)

viewer = napari.Viewer()
viewer.window.add_plugin_dock_widget(plugin_name='napari-micromanager')

napari.run()

In [ ]:
import napari
viewer = napari.Viewer()
viewer.window.add_plugin_dock_widget(
    plugin_name='napari-micromanager',
)
core = UniMMCore()
core.loadPyDevice("Camera", SimCameraDevice())
#core.loadPyDevice("XYStage", SimStageDevice())
core.initializeDevice("Camera")
#core.initializeDevice("XYStage")
core.setCameraDevice("Camera")
#core.setXYStageDevice("XYStage")
core.setExposure(50)
#core.startContinuousSequenceAcquisition(10)
napari.run()

In [1]:
from pymmcore_camera_sim import SimCameraDevice
from pymmcore_slm_sim import SimSLMDevice
from pymmcore_stage_sim import SimStageDevice
from pymmcore_state_device_sim import SimFilterWheelDevice, SimLEDDevice
from pymmcore_plus.experimental.unicore import UniMMCore
from pymmcore_shutter_sim import SimShutterDevice
from my_property_widget import SimPropertyWidget, SimPropertyWidges
import napari
from pymmcore_plus.experimental.unicore import UniMMCore
from property_test import MyMicromanagerToolbar


pygame 2.6.1 (SDL 2.28.4, Python 3.12.11)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
core = UniMMCore()

core.loadPyDevice("Camera", SimCameraDevice(core=core))
core.loadPyDevice("XYStage", SimStageDevice())
core.loadPyDevice("Filter Wheel", SimFilterWheelDevice())
core.loadPyDevice("LED", SimLEDDevice())
core.loadPyDevice("Shutter", SimShutterDevice())
core.initializeDevice("Camera")
core.initializeDevice("XYStage")
core.initializeDevice("Filter Wheel")
core.initializeDevice("LED")
core.initializeDevice("Shutter")
core.setCameraDevice("Camera")
core.setXYStageDevice("XYStage")
core.setShutterDevice("Shutter")

In [3]:
print(core.getLoadedDevices())
print(core.getDevicePropertyNames("Camera"))
for prop in core.getDevicePropertyNames("Camera"):
    print(prop, core.getPropertyType("Camera", prop))

('Camera', 'XYStage', 'Filter Wheel', 'LED', 'Shutter', 'Core')
('brightness', <Keyword.Binning: 'Binning'>, <Keyword.Exposure: 'Exposure'>)
brightness 2
Binning 3
Exposure 2


In [11]:
import napari
from pymmcore_widgets.device_properties import PropertiesWidget
from pymmcore_plus.experimental.unicore import UniMMCore

core = UniMMCore()
core.loadPyDevice("Camera", SimCameraDevice(core=core))
core.initializeDevice("Camera")

# Check properties
print(core.getDevicePropertyNames("Camera"))
# Should include 'my_custom_property'

viewer = napari.Viewer()
widget = PropertiesWidget(
    mmcore=core,
    property_name_pattern="brightness",
    device_label="Camera"
)
viewer.window.add_dock_widget(widget, name="Camera Properties")
napari.run()

('brightness', <Keyword.Binning: 'Binning'>, <Keyword.Exposure: 'Exposure'>)


In [3]:
viewer = napari.Viewer()
#viewer.window.add_dock_widget(widget=MyMicromanagerToolbar(viewer=viewer, core=core))
#viewer.window.add_dock_widget(widget=MyIllumination(mmcore=core))
viewer.window.add_plugin_dock_widget(plugin_name='napari-micromanager')
#viewer.window.add_dock_widget(widget=MyMicromanagerToolbar(viewer=viewer, core=core))
#viewer.window.add_dock_widget(widget=StageWidget(device="XYStage", mmcore=core), name="Stage")
#viewer.window.add_dock_widget(widget=MicroManagerToolbar(viewer), name="MicroManagerToolbar")
#viewer.window.add_dock_widget(widget=IlluminationWidget(mmcore=core), name="Illumination")
#viewer.window.add_dock_widget(widget=Illumination(core=core))
#viewer.window.add_dock_widget(widget=SimPropertyWidges(core=core))
#viewer.window.add_dock_widget(widget=SimPropertyWidget(device_label="Filter Wheel", prop_name="State", mmcore=core))
#viewer.window.add_dock_widget(widget=SimPropertyWidget(device_label="Filter Wheel", prop_name="Label", mmcore=core))

napari.run()

C:\Users\dario\anaconda3\envs\opto-loop\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
C:\Users\dario\anaconda3\envs\opto-loop\Lib\site-packages\napari_micromanager\main_window.py:51: FutureWarning: The `_dock_widgets` property is private and should not be used in any plugin code. Please use the `dock_widgets` property instead.
  if "MinMax" not in getattr(self.viewer.window, "_dock_widgets", []):


No SLM device found in core.
image before  [[177 196 179 ... 180 182 175]
 [182 180 177 ... 159 178 182]
 [183 173 167 ... 191 173 175]
 ...
 [178 171 191 ... 175 177 181]
 [180 171 192 ... 178 181 170]
 [191 179 180 ... 180 184 172]]
100.0
image after  [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
No SLM device found in core.
image before  [[173 182 173 ... 173 178 187]
 [185 174 178 ... 178 171 185]
 [191 180 185 ... 183 180 195]
 ...
 [190 185 173 ... 175 177 173]
 [166 185 176 ... 167 177 175]
 [166 173 169 ... 179 183 168]]
100.0
image after  [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
No SLM device found in core.
image before  [[194 167 173 ... 163 156 177]
 [189 162 167 ... 170 176 181]
 [1

Error creating widget for Camera-Binning: setText(self, a0: Optional[str]): argument 1 has unexpected type 'int'
Error creating widget for Filter Wheel-State: index 0 has type 'int' but 'str' is expected
Error creating widget for LED-State: index 0 has type 'int' but 'str' is expected


image before  [[173 168 168 ... 177 188 185]
 [184 177 170 ... 186 178 173]
 [191 167 183 ... 178 183 177]
 ...
 [181 170 165 ... 188 177 180]
 [177 170 180 ... 163 174 198]
 [177 173 184 ... 169 180 191]]
100.0
image after  [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
No SLM device found in core.
image before  [[172 172 177 ... 160 184 179]
 [190 179 180 ... 179 184 174]
 [172 181 174 ... 164 174 187]
 ...
 [173 170 171 ... 173 170 174]
 [165 176 193 ... 166 180 187]
 [165 186 170 ... 170 187 179]]
100.0
image after  [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
No SLM device found in core.
image before  [[177 178 180 ... 187 184 184]
 [177 192 185 ... 184 182 178]
 [187 183 184 ... 179 187 171]
 

image before  [[184 192 178 ... 183 178 163]
 [198 169 183 ... 182 175 174]
 [179 180 165 ... 166 183 192]
 ...
 [178 182 188 ... 196 180 186]
 [172 185 191 ... 168 173 190]
 [183 182 172 ... 170 183 160]]
0.5
image after  [[92 96 89 ... 92 89 82]
 [99 84 92 ... 91 88 87]
 [90 90 82 ... 83 92 96]
 ...
 [89 91 94 ... 98 90 93]
 [86 92 96 ... 84 86 95]
 [92 91 86 ... 85 92 80]]
No SLM device found in core.


image before  [[176 179 169 ... 190 180 177]
 [177 169 187 ... 178 182 178]
 [190 163 191 ... 177 177 178]
 ...
 [181 166 166 ... 192 167 175]
 [180 193 181 ... 177 193 174]
 [180 176 179 ... 183 185 170]]
0.5
image after  [[88 90 84 ... 95 90 88]
 [88 84 94 ... 89 91 89]
 [95 82 96 ... 88 88 89]
 ...
 [90 83 83 ... 96 84 88]
 [90 96 90 ... 88 96 87]
 [90 88 90 ... 92 92 85]]
No SLM device found in core.


image before  [[170 174 172 ... 168 174 174]
 [173 190 173 ... 178 183 161]
 [170 185 191 ... 170 198 175]
 ...
 [185 180 182 ... 192 188 172]
 [191 178 180 ... 174 191 187]
 [186 173 187 ... 186 180 169]]
0.5
image after  [[85 87 86 ... 84 87 87]
 [86 95 86 ... 89 92 80]
 [85 92 96 ... 85 99 88]
 ...
 [92 90 91 ... 96 94 86]
 [96 89 90 ... 87 96 94]
 [93 86 94 ... 93 90 84]]
No SLM device found in core.
image before  [[180 179 190 ... 170 169 170]
 [182 187 170 ... 179 175 170]
 [172 182 186 ... 191 181 168]
 ...
 [166 163 172 ... 190 180 198]
 [180 187 171 ... 181 193 169]
 [184 180 180 ... 184 184 182]]
0.5
image after  [[90 90 95 ... 85 84 85]
 [91 94 85 ... 90 88 85]
 [86 91 93 ... 96 90 84]
 ...
 [83 82 86 ... 95 90 99]
 [90 94 86 ... 90 96 84]
 [92 90 90 ... 92 92 91]]
No SLM device found in core.
image before  [[177 183 193 ... 180 184 186]
 [184 190 192 ... 173 177 159]
 [180 181 178 ... 184 173 165]
 ...
 [185 169 178 ... 173 180 186]
 [180 181 171 ... 174 183 182]
 [180 177 

red -> all cell
fared -> nucleus

others -> noise

exposure time -> everything will be multiplied (cutoff min and max) with longer exposure
expoasure time -> no light (black image) shorter exposure time



In [ ]:
core.getLoadedDevices()

In [12]:
from pymmcore_plus import PropertyType


print(PropertyType.Float)

2


In [4]:
for x in core.iterDevices(as_object=False):
    print(x)

Camera
XYStage
Filter Wheel
LED
Shutter
Core


In [ ]:
core.getDevicePropertyNames("Camera")

In [13]:
core.getPropertyType("Camera", "test_brightness")

float

In [10]:
for x in core.iterProperties(property_name_pattern="(Intensity|Power|Level|test)s?"):
    print(x)

<Property 'Camera::test_brightness' on UniMMCore at 0x1bee9c29c70 with 5 devices: value=100.0>


In [7]:
for i, (dev, prop) in enumerate(core.iterProperties(property_name_pattern="(Intensity|Power|Level|Brightness|test)s?", as_object=False)):
    print((i, dev, prop))

TypeError: cannot unpack non-iterable DeviceProperty object

In [ ]:
from pymmcore_plus import PropertyType

print(PropertyType.Float)

In [ ]:
from pymmcore_plus import CMMCorePlus
import napari


viewer = napari.Viewer()

mmc = CMMCorePlus.instance()
#mmc.loadSystemConfiguration()

viewer.window.add_plugin_dock_widget(plugin_name='napari-micromanager')

napari.run()

In [ ]:
from pymmcore_plus import DeviceType


In [ ]:
core.getShutterOpen(shutterLabel='Shutter')

In [ ]:
core.setShutterOpen(True)

In [ ]:
core.getShutterOpen(shutterLabel='Shutter')

In [ ]:
core